//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasTest.XCA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", ConfigurationName="XCA.IQuery")]
    public interface IQuery {
        
        // CODEGEN: Generating message contract since the wrapper name (AdhocQueryRequest) of message AdhocQueryRequest does not match the default value (CrossGatewayQueryRequest)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:ihe:iti:2007:CrossGatewayQueryAsync")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistryObject))]
        void CrossGatewayQueryRequest(TexasTest.XCA.AdhocQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:ihe:iti:2007:CrossGatewayQueryAsync")]
        System.Threading.Tasks.Task CrossGatewayQueryRequestAsync(TexasTest.XCA.AdhocQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:CrossGatewayQuery", ReplyAction="urn:ihe:iti:2007:CrossGatewayQueryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistryObject))]
        TexasTest.XCA.AdhocQueryResponse CrossGatewayQuerySyncRequest(TexasTest.XCA.AdhocQueryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:CrossGatewayQuery", ReplyAction="urn:ihe:iti:2007:CrossGatewayQueryResponse")]
        System.Threading.Tasks.Task<TexasTest.XCA.AdhocQueryResponse> CrossGatewayQuerySyncRequestAsync(TexasTest.XCA.AdhocQueryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0")]
    public partial class ResponseOption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReturnType returnTypeField;
        
        private string returnComposedObjectsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ReturnType returnType {
            get {
                return this.returnTypeField;
            }
            set {
                this.returnTypeField = value;
                this.RaisePropertyChanged("returnType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnComposedObjects {
            get {
                return this.returnComposedObjectsField;
            }
            set {
                this.returnComposedObjectsField = value;
                this.RaisePropertyChanged("returnComposedObjects");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0")]
    public enum ReturnType {
        
        /// <remarks/>
        LeafClass,
        
        /// <remarks/>
        ObjectRef,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:iti:xds-b:2007")]
    public partial class DocumentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string homeCommunityIdField;
        
        private string repositoryUniqueIdField;
        
        private string documentUniqueIdField;
        
        private string newRepositoryUniqueIdField;
        
        private string newDocumentUniqueIdField;
        
        private string mimeTypeField;
        
        private byte[] documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HomeCommunityId {
            get {
                return this.homeCommunityIdField;
            }
            set {
                this.homeCommunityIdField = value;
                this.RaisePropertyChanged("HomeCommunityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RepositoryUniqueId {
            get {
                return this.repositoryUniqueIdField;
            }
            set {
                this.repositoryUniqueIdField = value;
                this.RaisePropertyChanged("RepositoryUniqueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocumentUniqueId {
            get {
                return this.documentUniqueIdField;
            }
            set {
                this.documentUniqueIdField = value;
                this.RaisePropertyChanged("DocumentUniqueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NewRepositoryUniqueId {
            get {
                return this.newRepositoryUniqueIdField;
            }
            set {
                this.newRepositoryUniqueIdField = value;
                this.RaisePropertyChanged("NewRepositoryUniqueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NewDocumentUniqueId {
            get {
                return this.newDocumentUniqueIdField;
            }
            set {
                this.newDocumentUniqueIdField = value;
                this.RaisePropertyChanged("NewDocumentUniqueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public partial class RegistryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RegistryErrorList registryErrorListField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RegistryErrorList RegistryErrorList {
            get {
                return this.registryErrorListField;
            }
            set {
                this.registryErrorListField = value;
                this.RaisePropertyChanged("RegistryErrorList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public partial class RegistryErrorList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RegistryError[] registryErrorField;
        
        private string highestSeverityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryError", Order=0)]
        public RegistryError[] RegistryError {
            get {
                return this.registryErrorField;
            }
            set {
                this.registryErrorField = value;
                this.RaisePropertyChanged("RegistryError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string highestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
                this.RaisePropertyChanged("highestSeverity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public partial class RegistryError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeContextField;
        
        private string errorCodeField;
        
        private string severityField;
        
        private string locationField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeContext {
            get {
                return this.codeContextField;
            }
            set {
                this.codeContextField = value;
                this.RaisePropertyChanged("codeContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:iti:xds-b:2007")]
    public partial class DocumentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string homeCommunityIdField;
        
        private string repositoryUniqueIdField;
        
        private string documentUniqueIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HomeCommunityId {
            get {
                return this.homeCommunityIdField;
            }
            set {
                this.homeCommunityIdField = value;
                this.RaisePropertyChanged("HomeCommunityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RepositoryUniqueId {
            get {
                return this.repositoryUniqueIdField;
            }
            set {
                this.repositoryUniqueIdField = value;
                this.RaisePropertyChanged("RepositoryUniqueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocumentUniqueId {
            get {
                return this.documentUniqueIdField;
            }
            set {
                this.documentUniqueIdField = value;
                this.RaisePropertyChanged("DocumentUniqueId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class ObjectRef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string homeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
                this.RaisePropertyChanged("home");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class VersionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionNameField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string versionName {
            get {
                return this.versionNameField;
            }
            set {
                this.versionNameField = value;
                this.RaisePropertyChanged("versionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("comment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class LocalizedString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string charsetField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
                this.RaisePropertyChanged("charset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Association))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryPackage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtrinsicObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExternalIdentifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Classification))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class RegistryObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Slot[] slotField;
        
        private LocalizedString[] nameField;
        
        private LocalizedString[] descriptionField;
        
        private VersionInfo versionInfoField;
        
        private Classification[] classificationField;
        
        private ExternalIdentifier[] externalIdentifierField;
        
        private string accessControlPolicyField;
        
        private string idField;
        
        private string lidField;
        
        private string objectTypeField;
        
        private string homeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Slot", Order=0)]
        public Slot[] Slot {
            get {
                return this.slotField;
            }
            set {
                this.slotField = value;
                this.RaisePropertyChanged("Slot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalizedString[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalizedString[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionInfo VersionInfo {
            get {
                return this.versionInfoField;
            }
            set {
                this.versionInfoField = value;
                this.RaisePropertyChanged("VersionInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Classification", Order=4)]
        public Classification[] Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("Classification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalIdentifier", Order=5)]
        public ExternalIdentifier[] ExternalIdentifier {
            get {
                return this.externalIdentifierField;
            }
            set {
                this.externalIdentifierField = value;
                this.RaisePropertyChanged("ExternalIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string accessControlPolicy {
            get {
                return this.accessControlPolicyField;
            }
            set {
                this.accessControlPolicyField = value;
                this.RaisePropertyChanged("accessControlPolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lid {
            get {
                return this.lidField;
            }
            set {
                this.lidField = value;
                this.RaisePropertyChanged("lid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string objectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
                this.RaisePropertyChanged("objectType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
                this.RaisePropertyChanged("home");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class Slot : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Value[] valueListField;
        
        private string nameField;
        
        private string slotTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Value[] ValueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
                this.RaisePropertyChanged("ValueList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slotType {
            get {
                return this.slotTypeField;
            }
            set {
                this.slotTypeField = value;
                this.RaisePropertyChanged("slotType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class Value : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string value1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
                this.RaisePropertyChanged("Value1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class Classification : RegistryObject {
        
        private string classificationSchemeField;
        
        private string classifiedObjectField;
        
        private string classificationNodeField;
        
        private string nodeRepresentationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string classificationScheme {
            get {
                return this.classificationSchemeField;
            }
            set {
                this.classificationSchemeField = value;
                this.RaisePropertyChanged("classificationScheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string classifiedObject {
            get {
                return this.classifiedObjectField;
            }
            set {
                this.classifiedObjectField = value;
                this.RaisePropertyChanged("classifiedObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string classificationNode {
            get {
                return this.classificationNodeField;
            }
            set {
                this.classificationNodeField = value;
                this.RaisePropertyChanged("classificationNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nodeRepresentation {
            get {
                return this.nodeRepresentationField;
            }
            set {
                this.nodeRepresentationField = value;
                this.RaisePropertyChanged("nodeRepresentation");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class ExternalIdentifier : RegistryObject {
        
        private string registryObjectField;
        
        private string identificationSchemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string registryObject {
            get {
                return this.registryObjectField;
            }
            set {
                this.registryObjectField = value;
                this.RaisePropertyChanged("registryObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string identificationScheme {
            get {
                return this.identificationSchemeField;
            }
            set {
                this.identificationSchemeField = value;
                this.RaisePropertyChanged("identificationScheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class Association : RegistryObject {
        
        private string associationTypeField;
        
        private string sourceObjectField;
        
        private string targetObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string associationType {
            get {
                return this.associationTypeField;
            }
            set {
                this.associationTypeField = value;
                this.RaisePropertyChanged("associationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string sourceObject {
            get {
                return this.sourceObjectField;
            }
            set {
                this.sourceObjectField = value;
                this.RaisePropertyChanged("sourceObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string targetObject {
            get {
                return this.targetObjectField;
            }
            set {
                this.targetObjectField = value;
                this.RaisePropertyChanged("targetObject");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryPackage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtrinsicObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class RegistryEntry : RegistryObject {
        
        private string majorVersionField;
        
        private string minorVersionField;
        
        private string statusField;
        
        private string userVersionField;
        
        public RegistryEntry() {
            this.majorVersionField = "1";
            this.minorVersionField = "0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string majorVersion {
            get {
                return this.majorVersionField;
            }
            set {
                this.majorVersionField = value;
                this.RaisePropertyChanged("majorVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string minorVersion {
            get {
                return this.minorVersionField;
            }
            set {
                this.minorVersionField = value;
                this.RaisePropertyChanged("minorVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userVersion {
            get {
                return this.userVersionField;
            }
            set {
                this.userVersionField = value;
                this.RaisePropertyChanged("userVersion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class RegistryPackage : RegistryEntry {
        
        private RegistryObjectList registryObjectListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RegistryObjectList RegistryObjectList {
            get {
                return this.registryObjectListField;
            }
            set {
                this.registryObjectListField = value;
                this.RaisePropertyChanged("RegistryObjectList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class RegistryObjectList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExtrinsicObject[] extrinsicObjectField;
        
        private RegistryPackage[] registryPackageField;
        
        private Classification[] classificationField;
        
        private Association[] associationField;
        
        private ObjectRef[] objectRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtrinsicObject", Order=0)]
        public ExtrinsicObject[] ExtrinsicObject {
            get {
                return this.extrinsicObjectField;
            }
            set {
                this.extrinsicObjectField = value;
                this.RaisePropertyChanged("ExtrinsicObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryPackage", Order=1)]
        public RegistryPackage[] RegistryPackage {
            get {
                return this.registryPackageField;
            }
            set {
                this.registryPackageField = value;
                this.RaisePropertyChanged("RegistryPackage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Classification", Order=2)]
        public Classification[] Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("Classification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Association", Order=3)]
        public Association[] Association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
                this.RaisePropertyChanged("Association");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectRef", Order=4)]
        public ObjectRef[] ObjectRef {
            get {
                return this.objectRefField;
            }
            set {
                this.objectRefField = value;
                this.RaisePropertyChanged("ObjectRef");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class ExtrinsicObject : RegistryEntry {
        
        private string mimeTypeField;
        
        private bool isOpaqueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isOpaque {
            get {
                return this.isOpaqueField;
            }
            set {
                this.isOpaqueField = value;
                this.RaisePropertyChanged("isOpaque");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    public partial class AdhocQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Slot[] slotField;
        
        private string idField;
        
        private string homeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Slot", Order=0)]
        public Slot[] Slot {
            get {
                return this.slotField;
            }
            set {
                this.slotField = value;
                this.RaisePropertyChanged("Slot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
                this.RaisePropertyChanged("home");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdhocQueryRequest", WrapperNamespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", IsWrapped=true)]
    public partial class AdhocQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", Order=0)]
        public TexasTest.XCA.ResponseOption ResponseOption;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
        public TexasTest.XCA.AdhocQuery AdhocQuery;
        
        public AdhocQueryRequest() {
        }
        
        public AdhocQueryRequest(TexasTest.XCA.ResponseOption ResponseOption, TexasTest.XCA.AdhocQuery AdhocQuery) {
            this.ResponseOption = ResponseOption;
            this.AdhocQuery = AdhocQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdhocQueryResponse", WrapperNamespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", IsWrapped=true)]
    public partial class AdhocQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
        public TexasTest.XCA.RegistryObjectList RegistryObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
        public TexasTest.XCA.RegistryErrorList RegistryErrorList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
        
        public AdhocQueryResponse() {
        }
        
        public AdhocQueryResponse(TexasTest.XCA.RegistryObjectList RegistryObjectList, TexasTest.XCA.RegistryErrorList RegistryErrorList, System.Xml.XmlAttribute[] AnyAttr) {
            this.RegistryObjectList = RegistryObjectList;
            this.RegistryErrorList = RegistryErrorList;
            this.AnyAttr = AnyAttr;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueryChannel : TexasTest.XCA.IQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryClient : System.ServiceModel.ClientBase<TexasTest.XCA.IQuery>, TexasTest.XCA.IQuery {
        
        public QueryClient() {
        }
        
        public QueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TexasTest.XCA.IQuery.CrossGatewayQueryRequest(TexasTest.XCA.AdhocQueryRequest request) {
            base.Channel.CrossGatewayQueryRequest(request);
        }
        
        public void CrossGatewayQueryRequest(TexasTest.XCA.ResponseOption ResponseOption, TexasTest.XCA.AdhocQuery AdhocQuery) {
            TexasTest.XCA.AdhocQueryRequest inValue = new TexasTest.XCA.AdhocQueryRequest();
            inValue.ResponseOption = ResponseOption;
            inValue.AdhocQuery = AdhocQuery;
            ((TexasTest.XCA.IQuery)(this)).CrossGatewayQueryRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task TexasTest.XCA.IQuery.CrossGatewayQueryRequestAsync(TexasTest.XCA.AdhocQueryRequest request) {
            return base.Channel.CrossGatewayQueryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task CrossGatewayQueryRequestAsync(TexasTest.XCA.ResponseOption ResponseOption, TexasTest.XCA.AdhocQuery AdhocQuery) {
            TexasTest.XCA.AdhocQueryRequest inValue = new TexasTest.XCA.AdhocQueryRequest();
            inValue.ResponseOption = ResponseOption;
            inValue.AdhocQuery = AdhocQuery;
            return ((TexasTest.XCA.IQuery)(this)).CrossGatewayQueryRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TexasTest.XCA.AdhocQueryResponse TexasTest.XCA.IQuery.CrossGatewayQuerySyncRequest(TexasTest.XCA.AdhocQueryRequest request) {
            return base.Channel.CrossGatewayQuerySyncRequest(request);
        }
        
        public TexasTest.XCA.RegistryObjectList CrossGatewayQuerySyncRequest(TexasTest.XCA.ResponseOption ResponseOption, TexasTest.XCA.AdhocQuery AdhocQuery, out TexasTest.XCA.RegistryErrorList RegistryErrorList, out System.Xml.XmlAttribute[] AnyAttr) {
            TexasTest.XCA.AdhocQueryRequest inValue = new TexasTest.XCA.AdhocQueryRequest();
            inValue.ResponseOption = ResponseOption;
            inValue.AdhocQuery = AdhocQuery;
            TexasTest.XCA.AdhocQueryResponse retVal = ((TexasTest.XCA.IQuery)(this)).CrossGatewayQuerySyncRequest(inValue);
            RegistryErrorList = retVal.RegistryErrorList;
            AnyAttr = retVal.AnyAttr;
            return retVal.RegistryObjectList;
        }
        
        public System.Threading.Tasks.Task<TexasTest.XCA.AdhocQueryResponse> CrossGatewayQuerySyncRequestAsync(TexasTest.XCA.AdhocQueryRequest request) {
            return base.Channel.CrossGatewayQuerySyncRequestAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ihe:iti:xds-b:2007", ConfigurationName="XCA.IRetrieve")]
    public interface IRetrieve {
        
        // CODEGEN: Generating message contract since the wrapper name (RetrieveDocumentSetRequest) of message RetrieveDocumentSetRequest does not match the default value (CrossGatewayRetrieveRequest)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:ihe:iti:2007:CrossGatewayRetrieveAsync")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistryObject))]
        void CrossGatewayRetrieveRequest(TexasTest.XCA.RetrieveDocumentSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:ihe:iti:2007:CrossGatewayRetrieveAsync")]
        System.Threading.Tasks.Task CrossGatewayRetrieveRequestAsync(TexasTest.XCA.RetrieveDocumentSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:CrossGatewayRetrieve", ReplyAction="urn:ihe:iti:2007:CrossGatewayRetrieveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistryObject))]
        TexasTest.XCA.RetrieveDocumentSetResponse CrossGatewayRetrieveSyncRequest(TexasTest.XCA.RetrieveDocumentSetRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:CrossGatewayRetrieve", ReplyAction="urn:ihe:iti:2007:CrossGatewayRetrieveResponse")]
        System.Threading.Tasks.Task<TexasTest.XCA.RetrieveDocumentSetResponse> CrossGatewayRetrieveSyncRequestAsync(TexasTest.XCA.RetrieveDocumentSetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveDocumentSetRequest", WrapperNamespace="urn:ihe:iti:xds-b:2007", IsWrapped=true)]
    public partial class RetrieveDocumentSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ihe:iti:xds-b:2007", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DocumentRequest")]
        public TexasTest.XCA.DocumentRequest[] DocumentRequest;
        
        public RetrieveDocumentSetRequest() {
        }
        
        public RetrieveDocumentSetRequest(TexasTest.XCA.DocumentRequest[] DocumentRequest) {
            this.DocumentRequest = DocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveDocumentSetResponse", WrapperNamespace="urn:ihe:iti:xds-b:2007", IsWrapped=true)]
    public partial class RetrieveDocumentSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
        public TexasTest.XCA.RegistryResponse RegistryResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ihe:iti:xds-b:2007", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("DocumentResponse")]
        public TexasTest.XCA.DocumentResponse[] DocumentResponse;
        
        public RetrieveDocumentSetResponse() {
        }
        
        public RetrieveDocumentSetResponse(TexasTest.XCA.RegistryResponse RegistryResponse, TexasTest.XCA.DocumentResponse[] DocumentResponse) {
            this.RegistryResponse = RegistryResponse;
            this.DocumentResponse = DocumentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetrieveChannel : TexasTest.XCA.IRetrieve, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveClient : System.ServiceModel.ClientBase<TexasTest.XCA.IRetrieve>, TexasTest.XCA.IRetrieve {
        
        public RetrieveClient() {
        }
        
        public RetrieveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetrieveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TexasTest.XCA.IRetrieve.CrossGatewayRetrieveRequest(TexasTest.XCA.RetrieveDocumentSetRequest request) {
            base.Channel.CrossGatewayRetrieveRequest(request);
        }
        
        public void CrossGatewayRetrieveRequest(TexasTest.XCA.DocumentRequest[] DocumentRequest) {
            TexasTest.XCA.RetrieveDocumentSetRequest inValue = new TexasTest.XCA.RetrieveDocumentSetRequest();
            inValue.DocumentRequest = DocumentRequest;
            ((TexasTest.XCA.IRetrieve)(this)).CrossGatewayRetrieveRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task TexasTest.XCA.IRetrieve.CrossGatewayRetrieveRequestAsync(TexasTest.XCA.RetrieveDocumentSetRequest request) {
            return base.Channel.CrossGatewayRetrieveRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task CrossGatewayRetrieveRequestAsync(TexasTest.XCA.DocumentRequest[] DocumentRequest) {
            TexasTest.XCA.RetrieveDocumentSetRequest inValue = new TexasTest.XCA.RetrieveDocumentSetRequest();
            inValue.DocumentRequest = DocumentRequest;
            return ((TexasTest.XCA.IRetrieve)(this)).CrossGatewayRetrieveRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TexasTest.XCA.RetrieveDocumentSetResponse TexasTest.XCA.IRetrieve.CrossGatewayRetrieveSyncRequest(TexasTest.XCA.RetrieveDocumentSetRequest request) {
            return base.Channel.CrossGatewayRetrieveSyncRequest(request);
        }
        
        public TexasTest.XCA.RegistryResponse CrossGatewayRetrieveSyncRequest(TexasTest.XCA.DocumentRequest[] DocumentRequest, out TexasTest.XCA.DocumentResponse[] DocumentResponse) {
            TexasTest.XCA.RetrieveDocumentSetRequest inValue = new TexasTest.XCA.RetrieveDocumentSetRequest();
            inValue.DocumentRequest = DocumentRequest;
            TexasTest.XCA.RetrieveDocumentSetResponse retVal = ((TexasTest.XCA.IRetrieve)(this)).CrossGatewayRetrieveSyncRequest(inValue);
            DocumentResponse = retVal.DocumentResponse;
            return retVal.RegistryResponse;
        }
        
        public System.Threading.Tasks.Task<TexasTest.XCA.RetrieveDocumentSetResponse> CrossGatewayRetrieveSyncRequestAsync(TexasTest.XCA.RetrieveDocumentSetRequest request) {
            return base.Channel.CrossGatewayRetrieveSyncRequestAsync(request);
        }
    }
}
